import type { Metadata } from "next";
import "./globals.css";
import LayoutApp from "./component/layout/layout_app";



export const metadata: Metadata = {
  title: "CARLO FIRE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <LayoutApp>
          {children}
        </LayoutApp>
      </body>
    </html>
  );
}
